collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1899642
color:
  saturation: 0
  brandStrength: 0.2924604
  lightness: 0
  brandColors:
    - '#AFC2C8'
    - '#6D7162'
    - '#B89087'
    - '#FF4D49'
    - '#B72F2D'
  rhythmicContrast: 0.6326165
navigation: []
layout_spectrum: 0.3200043
name: be team
